### ISSUE TITLE
home button doesn't work before first shoot

### ISSUE THREAD

**Issue by schwabdidier** [schwabdidier/GazePlay#156] opened 2018-01-17 19:48 UTC
at least for cream pie

**Comment by YannRobert** [comment] 2018-01-17 20:07
I can't reproduce

**Comment by schwabdidier** [comment] 2018-01-17 20:12
As long as home button is displayed, I can't click it. If I shoot or if the button disappear and appear again, I can click.

**Comment by WaffleBuffer** [comment] 2018-01-29 09:14
Is this issue still up ? Because i can't reproduce the bug either.

**Comment by YannRobert** [comment] 2018-01-29 09:34
If I remember correctly I managed to reproduce on Windows, but not on Linux.

**Comment by schwabdidier** [comment] 2018-01-29 09:50
I still have the bug on my laptop with mac OS

**Comment by YannRobert** [comment] 2018-01-29 21:44
Yes, I can still reproduce on Windows

**Comment by YannRobert** [comment] 2018-02-12 21:04
fixed in 1.2

**Closed by YannRobert** 2018-02-12 21:04 UTC
Labels: bug
