### ISSUE TITLE
Black bar in full screen

### ISSUE THREAD

**Issue by kuhlkrein** [schwabdidier/GazePlay#469] opened 2018-06-04 10:58 UTC
I don't know why but when I'm in full-screen mode it seems that there is a black rectangle on the bottom of the screen (at the position of the previous control panel). It disappears when I exit the full-screen mode

**Comment by kuhlkrein** [comment] 2018-06-04 11:01
Maybe a problem in the Game Context?

**Comment by WaffleBuffer** [comment] 2018-06-05 07:33
Does this appear in games or in menu or everywhere ? Also please provide a screenshot showing the issue.

**Comment by kuhlkrein** [comment] 2018-06-05 07:44
On games. But when the game ends and restarts (at the end), it sets to a normal full screen.

![image](https://user-images.githubusercontent.com/24478346/40962135-f4b363ac-68a4-11e8-9c81-eb3f186b7e95.png)

**Comment by WaffleBuffer** [comment] 2018-06-05 07:57
Do you have this is Colors! game because for me, this black part is in nearly all the games except colors! Also, for me it stays here even if i change fullscreen mode

**Comment by kuhlkrein** [comment] 2018-06-05 09:05
On bottom right side yes 

![image](https://user-images.githubusercontent.com/24478346/40966285-5c92a860-68b0-11e8-965f-4a49732a8382.png)

**Comment by WaffleBuffer** [comment] 2018-06-05 09:08
Actually, the problem is just that height for rectangles is not dynamically adapting. I will fix it. For color it is the same problem.

**Comment by WaffleBuffer** [comment] 2018-06-05 11:32
I fixed this in my last PR (not merged yet) BUT those kind of fixes are games dependant. For exemple, you should also adapt dynamically the position of the displayed date and the position of the cage.

**Comment by WaffleBuffer** [comment] 2018-06-05 11:32
Also there is this black bar on other games with background like where is the color. The same fix could be applied for those games.

**Comment by kuhlkrein** [comment] 2018-06-06 06:53
But it was working before on games with background...  without changing it inside the game. And it works when it relaunches the games... So I think we can solve it for the general case..

**Comment by WaffleBuffer** [comment] 2018-06-06 06:57
Hmm... For me the games always stays as they are (with the black line below). I'm on Linux. I've done it this way because when you add a colored border to the GameContext root, you see that it has the right size. If you have any clue of solving the problem in general tell us. Also this problem doesn't seem to appear in color game (as i've created it i'm using it as a reference) and the color tool box was made to not take all the available height (i've changed it because it is better this way).

**Comment by kuhlkrein** [comment] 2018-06-06 12:46
I just solved the problem easily on linux (i think it's the same on windows),  i just replace a "gaming root" by "root" :) I will push it via Melanie's account.

**Closed** 2018-06-06 12:58 UTC
